### ISSUE TITLE
Use CSS variables for easier changes of values.

### ISSUE THREAD

**Issue by rahulc0dy** [InvinQueste/Gallery-Database-Software#3]
# Problem
**There are multiple instances of same colors and other values in the stylesheets**

example:
```css
border: 2px solid rgba(255, 255, 255, .2);
```

## Solution
use css variables for these values to make updates to these properties easier.

for example:
the above can be segregated to 
```css
:root {
    --border-color-primary: rgba(255, 255, 255, .2);
}

.some-selector {
    border: 2px solid var(--border-color-primary);
}

.some-other-selector {
    border: 5px dashed var(--border-color-primary);
}
```

This will make it easier to update the values and colors, as they will need to be updated in only one place;

### Additional
Also usage of wider color gamut is preferred. (hsl or oklch)
